# Generated by Django 5.0.1 on 2024-01-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'permissions': (('can_lead_approval', 'to approve leads'),)},
        ),
    ]
