# Generated by Django 5.0.1 on 2024-01-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_lead_agent_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
