# Generated by Django 5.0.1 on 2024-01-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_lead_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
